 
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adrianamoralesc19
      - MONGO_INITDB_ROOT_PASSWORD=i77nAfZHKQf4J3Id

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://adrianamoralesc19:i77nAfZHKQf4J3Id@cluster1.nxrp8.mongodb.net/auth-db?retryWrites=true&w=majority
    depends_on:
      - mongo
    env_file:
      - ./auth-service/.env
  products-service:
    build:
      context: ./products-service
    container_name: products-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb+srv://adrianamoralesc19:i77nAfZHKQf4J3Id@cluster1.nxrp8.mongodb.net/products-db?retryWrites=true&w=majority
    depends_on:
      - mongo
    env_file:
      - ./products-service/.env